name: Publish to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Scope package name for GitHub Packages
        run: |
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            pkg.name = '@kesi03/' + pkg.name.replace(/^@.*\//, '');
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
            console.log('✅ Scoped package name:', pkg.name);
          "

      - name: Configure .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Build (optional)
        run: pnpm build || echo "No build step"

      - name: Publish to GitHub Packages
        run: pnpm publish --registry=https://npm.pkg.github.com/ --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    